// lib/menu.ts
import { MenuItemData } from './types'

export const menuItems: MenuItemData[] = [
  // ── PIZZA ──────────────────────────────────────────────
  { id: 'p1',  category: 'pizza', name: 'Lambertseter Spesial Pizza', description: 'Biff, skinke, løk og paprika',
    sizes: [{ label: 'Normal', price: 269 }] },
  { id: 'p2',  category: 'pizza', name: 'Visuvio', description: 'Ost og skinke',
    sizes: [{ label: 'Normal', price: 234 }] },
  { id: 'p3',  category: 'pizza', name: 'Pepperoni Star', description: 'Pepperoni, ananas og paprika',
    sizes: [{ label: 'Normal', price: 250 }] },
  { id: 'p4',  category: 'pizza', name: 'Marco Polo', description: 'Skinke og ananas',
    sizes: [{ label: 'Normal', price: 244 }] },
  { id: 'p5',  category: 'pizza', name: 'Rafaele', description: 'Biff, pepperoni, løk og paprika',
    sizes: [{ label: 'Normal', price: 270 }] },
  { id: 'p6',  category: 'pizza', name: 'Mona Lisa', description: 'Hvitløk, marinert biff, løk og champignon',
    sizes: [{ label: 'Normal', price: 261 }] },
  { id: 'p7',  category: 'pizza', name: 'Mexicaneren', description: 'Kjøttdeig, skinke, løk, paprika og oliven',
    sizes: [{ label: 'Normal', price: 267 }] },
  { id: 'p8',  category: 'pizza', name: 'Vegetarianeren', description: 'Paprika, champignon, løk, oliven, tomat og mais',
    sizes: [{ label: 'Normal', price: 252 }] },
  { id: 'p9',  category: 'pizza', name: 'Milano', description: 'Marinert biff, løk og paprika',
    sizes: [{ label: 'Normal', price: 264 }] },
  { id: 'p10', category: 'pizza', name: 'Chicken George', description: 'Marinert kylling, løk og paprika',
    sizes: [{ label: 'Normal', price: 257 }] },
  { id: 'p11', category: 'pizza', name: 'Huglo', description: 'Marinert biff, kylling, løk, paprika og champignon',
    sizes: [{ label: 'Normal', price: 274 }] },
  { id: 'p12', category: 'pizza', name: 'Hot Zafari', description: 'Pepperoni, biff, løk og jalapeños',
    sizes: [{ label: 'Normal', price: 282 }] },
  { id: 'p13', category: 'pizza', name: 'Kebab Pizza', description: 'Kebabkjøtt, paprika, løk og mais',
    sizes: [{ label: 'Normal', price: 264 }] },
  { id: 'p14', category: 'pizza', name: 'American Way', description: 'Skinke, pepperoni, biff, bacon, løk, champignon og paprika',
    sizes: [{ label: 'Normal', price: 304 }] },
  { id: 'p15', category: 'pizza', name: 'Margaretha', description: 'Tomatsaus og ferske tomater',
    sizes: [{ label: 'Normal', price: 234 }] },
  { id: 'p16', category: 'pizza', name: 'New York City', description: 'Pepperoni, skinke, kjøttboller, løk, jalapeños og oliven',
    sizes: [{ label: 'Normal', price: 284 }] },
  { id: 'p17', category: 'pizza', name: 'Tommy Spesial', description: 'Skinke, biff, champignon og løk',
    sizes: [{ label: 'Normal', price: 264 }] },
  { id: 'p18', category: 'pizza', name: 'Stian Spesial', description: 'Skinke, pepperoni, biff og løk',
    sizes: [{ label: 'Normal', price: 276 }] },
  { id: 'p19', category: 'pizza', name: 'Robeen Spesial', description: 'Kylling, biff, kjøttdeig, nachochips, paprika og løk',
    sizes: [{ label: 'Normal', price: 276 }] },
  { id: 'p20', category: 'pizza', name: 'Raja Spesial', description: 'Tunfisk, tomat, oliven, jalapeños og løk',
    sizes: [{ label: 'Normal', price: 276 }] },
  { id: 'p21', category: 'pizza', name: 'Fifty Fifty Pizza', description: 'Halvt og halvt — velg to smaker',
    sizes: [{ label: 'Normal', price: 324 }] },
  { id: 'p22', category: 'pizza', name: 'Din Egen Pizza', description: 'Velg 6 garnityrer fra menyen',
    sizes: [{ label: 'Normal', price: 324 }] },

  // ── KEBAB ──────────────────────────────────────────────
  { id: 'k1', category: 'kebab', name: 'Kebab i Pitabrød', description: '',
    sizes: [{ label: 'Medium', price: 109 }, { label: 'Stor', price: 135 }] },
  { id: 'k2', category: 'kebab', name: 'Kyllingkebab i Pitabrød', description: '',
    sizes: [{ label: 'Medium', price: 139 }, { label: 'Stor', price: 159 }] },
  { id: 'k3', category: 'kebab', name: 'Biffkebab', description: '',
    sizes: [{ label: 'Medium', price: 205 }, { label: 'Stor', price: 235 }] },
  { id: 'k4', category: 'kebab', name: 'Kebabtallerken', description: '',
    sizes: [{ label: 'Medium', price: 169 }, { label: 'Stor', price: 190 }] },
  { id: 'k5', category: 'kebab', name: 'Kebabtallerken med drikke', description: '',
    sizes: [{ label: 'Medium', price: 189 }, { label: 'Stor', price: 209 }] },
  { id: 'k6', category: 'kebab', name: 'Kyllingkebabtallerken', description: '',
    sizes: [{ label: 'Medium', price: 189 }, { label: 'Stor', price: 204 }] },
  { id: 'k7', category: 'kebab', name: 'Kyllingkebabtallerken med drikke', description: '',
    sizes: [{ label: 'Medium', price: 209 }, { label: 'Stor', price: 234 }] },
  { id: 'k8', category: 'kebab', name: 'Biffkebabtallerken', description: '',
    sizes: [{ label: 'Medium', price: 249 }, { label: 'Stor', price: 289 }] },
  { id: 'k9', category: 'kebab', name: 'Biffkebabtallerken med drikke', description: '',
    sizes: [{ label: 'Medium', price: 279 }, { label: 'Stor', price: 319 }] },
  { id: 'k10', category: 'kebab', name: 'Shish Kebab Rull', description: '',
    sizes: [{ label: 'Medium', price: 140 }, { label: 'Stor', price: 170 }] },
  { id: 'k11', category: 'kebab', name: 'Falaffel i Rull', description: '',
    sizes: [{ label: 'Medium', price: 140 }, { label: 'Stor', price: 165 }] },
  { id: 'k12', category: 'kebab', name: 'Kylling i Rull', description: '',
    sizes: [{ label: 'Medium', price: 149 }, { label: 'Stor', price: 169 }] },
  { id: 'k13', category: 'kebab', name: 'Kebab i Rull', description: '',
    sizes: [{ label: 'Medium', price: 135 }, { label: 'Stor', price: 149 }] },

  // ── HAMBURGER ──────────────────────────────────────────
  { id: 'h1', category: 'hamburger', name: 'Hamburger', description: 'I brød med salat og dressing',
    sizes: [{ label: '100g', price: 129 }, { label: '160g', price: 149 }, { label: '190g', price: 174 }, { label: '255g', price: 182 }] },
  { id: 'h2', category: 'hamburger', name: 'Hamburger m/pommes frites', description: 'I brød med salat og dressing',
    sizes: [{ label: '100g', price: 159 }, { label: '160g', price: 179 }, { label: '190g', price: 199 }, { label: '255g', price: 210 }] },
  { id: 'h3', category: 'hamburger', name: 'Hamburger m/pommes frites og drikke', description: 'I brød med salat og dressing',
    sizes: [{ label: '100g', price: 179 }, { label: '160g', price: 199 }, { label: '190g', price: 209 }, { label: '255g', price: 229 }] },
  { id: 'h4', category: 'hamburger', name: 'Cheeseburger', description: 'I brød med salat og dressing',
    sizes: [{ label: '100g', price: 139 }, { label: '160g', price: 159 }, { label: '190g', price: 185 }, { label: '255g', price: 195 }] },
  { id: 'h5', category: 'hamburger', name: 'Cheeseburger m/pommes frites', description: 'I brød med salat og dressing',
    sizes: [{ label: '100g', price: 169 }, { label: '160g', price: 199 }, { label: '190g', price: 209 }, { label: '255g', price: 214 }] },
  { id: 'h6', category: 'hamburger', name: 'Cheeseburger m/pommes frites og drikke', description: 'I brød med salat og dressing',
    sizes: [{ label: '100g', price: 195 }, { label: '160g', price: 214 }, { label: '190g', price: 230 }, { label: '255g', price: 239 }] },
  { id: 'h7', category: 'hamburger', name: 'Fiskeburger', description: 'I brød med salat og dressing',
    sizes: [{ label: 'Normal', price: 139 }] },
  { id: 'h8', category: 'hamburger', name: 'Fiskeburger m/pommes frites', description: '',
    sizes: [{ label: 'Normal', price: 169 }] },
  { id: 'h9', category: 'hamburger', name: 'Fiskeburger m/pommes frites og drikke', description: '',
    sizes: [{ label: 'Normal', price: 195 }] },
  { id: 'h10', category: 'hamburger', name: 'Kyllingburger', description: '',
    sizes: [{ label: 'Normal', price: 139 }] },
  { id: 'h11', category: 'hamburger', name: 'Kyllingburger m/pommes frites', description: '',
    sizes: [{ label: 'Normal', price: 169 }] },
  { id: 'h12', category: 'hamburger', name: 'Kyllingburger m/pommes frites og drikke', description: '',
    sizes: [{ label: 'Normal', price: 195 }] },
  { id: 'h13', category: 'hamburger', name: 'Løvstekburger', description: '',
    sizes: [{ label: 'Normal', price: 155 }] },
  { id: 'h14', category: 'hamburger', name: 'Løvstektallerken m/pommes frites', description: '',
    sizes: [{ label: 'Normal', price: 189 }] },
  { id: 'h15', category: 'hamburger', name: 'Løvstektallerken m/pommes frites og drikke', description: '',
    sizes: [{ label: 'Normal', price: 200 }] },

  // ── SIDES ──────────────────────────────────────────────
  { id: 's1', category: 'sides', name: 'Pommes Frites', description: '',
    sizes: [{ label: 'Liten', price: 60 }, { label: 'Stor', price: 75 }] },
  { id: 's2', category: 'sides', name: 'Søt Potet Pommes Frites', description: '',
    sizes: [{ label: 'Liten', price: 89 }, { label: 'Stor', price: 99 }] },

  // ── SALAT ──────────────────────────────────────────────
  { id: 'sa1', category: 'salat', name: 'Kyllingsalat', description: 'Med mais, tomat og agurk',
    sizes: [{ label: 'Normal', price: 190 }] },

  // ── DRIKKE ─────────────────────────────────────────────
  { id: 'd1', category: 'drikke', name: 'Drikke', description: '',
    sizes: [{ label: '0,5 L', price: 39 }, { label: '1,5 L', price: 59 }] },
]

export const categories = [
  { id: 'alle',       label: '🍽️ Alle' },
  { id: 'pizza',      label: '🍕 Pizza' },
  { id: 'kebab',      label: '🥙 Kebab' },
  { id: 'hamburger',  label: '🍔 Burger' },
  { id: 'sides',      label: '🍟 Sides' },
  { id: 'salat',      label: '🥗 Salat' },
  { id: 'drikke',     label: '🥤 Drikke' },
] as const
